#docker build -t daroya.moneymeapi .
#docker run -d -p 8080:80 --name myapp daroya.moneymeapi
#docker tag daroya.moneymeapi registry.heroku.com/daroya-moneymeapi/web
#docker tag 89a7eb342b22 registry.heroku.com/daroya-moneymeapi/web
#docker push registry.heroku.com/daroya-moneymeapi/web
#heroku container:release web --app daroya-moneymeapi

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY Daroya.MoneymeAPI/Daroya.MoneymeAPI.csproj ./Daroya.MoneymeAPI/
COPY Daroya.MoneymeAPI.Database/Daroya.MoneymeAPI.Database.csproj ./Daroya.MoneymeAPI.Database/
COPY Daroya.MoneymeAPI.Models/Daroya.MoneymeAPI.Models.csproj ./Daroya.MoneymeAPI.Models/
COPY Daroya.MoneymeAPI.Services/Daroya.MoneymeAPI.Services.csproj ./Daroya.MoneymeAPI.Services/
RUN dotnet restore ./Daroya.MoneymeAPI/Daroya.MoneymeAPI.csproj
# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "Daroya.MoneymeAPI.dll"]